### ISSUE TITLE
Test button on initial menu not running

### ISSUE THREAD

**Issue by Gagenpreet** [NS-01/forked_enamel#1]
severity - Low
Version - vM
Component - Initial Menu
Platform - Windows Laptop
Java Version -  8 Update 161

Description:  Once a valid text file is opened using the test menu nothing happens beyond that.

Steps: Run app, click Test, choose file

Result: Nothing happens just closes the window.

Desired: Tests/runs the scenario.

**Comment by NS-01** [comment]
Please follow the instructions [here](https://github.com/NS-01/forked_enamel/tree/master/Authoring%20App%20Jars).
