### ISSUE TITLE
"Save and Create Scenario File" button in Scenario Creator window does not save file

### ISSUE THREAD

**Issue by gnuch** [NS-01/forked_enamel#2]
Severity:         Trivial
Version:          vM
Component:  Scenario Creator window
Platform:        PC
OS:                 Windows & Linux
Java Version:  8
Priority:          P5

Description:   When you click the Save and Create Scenario File, it brings up the "AuthoringApp view" window, but it does not save the file.

Steps: Run program. Click "New" button. Type a Scenario Title name. Click "Save and Create Scenario File" button.

Actual Results: "AuthoringApp view" window pops up but the file is not saved. 

Expected Result: File should be saved with the specified "Scenario Title."

Build Date: 2018-03-05

**Comment by NS-01** [comment]
This behaviour is not unexpected, but rather intended. The documentation clearly states that the"Save and Create Scenario File" button takes the user to the next stage of scenario creation by bringing up the "AuthoringApp view".
