### ISSUE TITLE
Save on the AuthoringApp view displays wrong message

### ISSUE THREAD

**Issue by khallman97** [NS-01/forked_enamel#3]
severity - Low
Version - vM
Component - AuthoringApp view
Platform - Windows Desktop
Java Version - 8 Update 161

**Description:** Once a file is saved onto a loction using the save button is displays the message that says: 
Saved recorded to sounds to:

**Steps:** Click on New in the main menu, select data for new project and click save and create scenario file
then click the save button and save anywhere. 

**Results:** A prompt message that says " Saved recorded sound to: "

**Desired:** A message that says the file is saved

**Comment by NS-01** [comment]
The issue has been resolved. The prompt message now says: "Saved scenario file to:".
